name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GO111MODULE: on

    # Intentionally use 22.04 instead of "latest" to
    # make this build reproducible.
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19']
      # Build all variants regardless of failures
      fail-fast: false
    name: Go ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v3
        with:
          # By default, the checkout action only fetches the last commit,
          # but we want to run DCO check against all commit messages.
          # Assuming that a pull request may have multiple commits,
          # fetching the single commit doesn't work for us.
          #
          # While DCO check (on Makefile) checks latest 20 commits,
          # the checkout action automatically creates a merge commit
          # for merging "master" into a pull request branch.
          # So we need to fetch 21 commits (including the merge commit)
          # to have 20 actual commits from a pull request.
          fetch-depth: 21
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: make deps
      - run: make
      - run: make lint
      - run: make test
